### ISSUE TITLE
doesn't repeat

### ISSUE THREAD

**Issue by MakeshiftAlways** [XtramCZ/auto-advertise-py#10]
hi idk if i am being really stupid, but i run the run file and it only sends the message once. my interval is at 100 minutes but it doesnt send it again, only when i run the script again. I tried keeping it open and it doesnt send. can u please help or am i being rlly stupid

**Comment by XtramCZ** [comment]
Hey, do you have **work_hours**, **avoid_spam** or **randomize_interval** enabled?

**Comment by MakeshiftAlways** [comment]
none of them are enabled, are they ment to?

**Comment by XtramCZ** [comment]
nope just checking, enable debug mode and try again if that fixes it. Or decrease the interval to like a minute and try it on a private server

**Comment by MakeshiftAlways** [comment]
it works in one server. but, the activity thing doesnt work. i set the values to "true" and "idle" but doesnt work

**Comment by XtramCZ** [comment]
Like I said - enable debug mode, there may be cooldowns etc.

About the activity, it's not perfected yet and I'll try to fix it
