### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by merryweatherhq** [XtramCZ/auto-advertise-py#11]
I have been getting this error for a while now, whenever i try to run the start.bat it just says ModuleNotFoundError. here are the pictures and yes I have installed the packages under requirements.txt
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159193737/f85ac0bd-36e3-469b-aa5b-53f32da24edc)
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159193737/99ffc09e-20c8-4ff2-99f8-87dc0e67356d)

**Comment by XtramCZ** [comment]
Hi, do you have installed multiple python versions? You can also try `py -m pip install -r requirements.txt` if that fixes it

**Comment by merryweatherhq** [comment]
Hmm, it fixed some part.
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159193737/e65c6157-e534-45c8-abd5-f2189d035dc7)
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159193737/54bfeb76-6dda-4cf9-b640-40bec761e8bd)
here is the output

**Comment by merryweatherhq** [comment]
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159193737/69ce643b-734c-4131-a54c-5abe4cdfe1e1)

**Comment by XtramCZ** [comment]
You somehow messed up your config, there should be one : on almost every line. Get a new one and do it again

**Comment by merryweatherhq** [comment]
I have downloada it over 8 times today, and same thing when it opens in .txt

**Comment by XtramCZ** [comment]
Well I'm sorry I can't help you with that.

**Comment by merryweatherhq** [comment]
I’ll just try the javascript one

**Comment by merryweatherhq** [comment]
ive got it to work but whenever it finished advertising it says this: 
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159193737/451f58b1-24de-4abc-b14a-1cb556865370)

**Comment by merryweatherhq** [comment]
Hi?

**Comment by XtramCZ** [comment]
Can you send your config? (without token and channel ids of course)
