### ISSUE TITLE
start.bat: command not found | PLEASE HELP

### ISSUE THREAD

**Issue by Zeolite2** [XtramCZ/auto-advertise-py#12]
I keep getting this error even though I have put everything inconfig.yml. I run the bot on Replit, I start it from the "start.bat" tab. Any idea why it is showing that. PLEASE HELP!

![bot problem](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/251f7e95-c28f-49e7-8bec-8e9eb35c5653)

**Comment by XtramCZ** [comment]
You can't run bat with *sh*, run the python file directly.

**Comment by XtramCZ** [comment]
I don't have experience with replit so I can't help you. Maybe the green "run" button at the top? You need to execute the command `python main.py` or `python3 main.py`

**Comment by Zeolite2** [comment]
When I click "Run" it shows that "start.bat: command not found". Where should I write that "python main.py or python3 main.py"?

**Comment by XtramCZ** [comment]
That runs the file. Like I said, you are going to have to try to fix it yourself as I don't know how to setup replit for python.

**Comment by Zeolite2** [comment]
It's the same for Replit, don't worry. But I really don't know how to fix it. Can you please check for me, I really need that bot, because it's easy to use? Please bro

**Comment by XtramCZ** [comment]
I can try tomorrow

**Comment by Zeolite2** [comment]
Yeah bro, please do it. I would really appreciate it. I really need it. So would you let me know when you try, it's pretty easy to navigate through Replit, don't worry.

**Comment by Zeolite2** [comment]
BTW can you tell me what that means "bash: start.bat: command not found"?

**Comment by XtramCZ** [comment]
"start.bat" is treated as a command (because it is not a .sh) but it doesn't exist.

**Comment by Zeolite2** [comment]
What does .sh mean? And btw did you manage to try it on Replit?

**Comment by XtramCZ** [comment]
https://stackoverflow.com/questions/13805295/whats-a-sh-file

Works on replit without issues for me.

**Comment by Zeolite2** [comment]
Very nice. How did you run it? Could you help me fix the issue with Replit for me, especially the one with "bash: start.bat: command not found"?

**Comment by XtramCZ** [comment]
I clicked on "create repl" and then "import from github > from URL" on the top right. I don't really know how to fix your issue, but try to do it like i said.

**Comment by Zeolite2** [comment]
I did it the same way, put the info in the config file and then click run. What did you do after putting the info in the config, did you add the command "start.bat" anywhere? Please help

**Comment by XtramCZ** [comment]
no, i didnt do anything else. Just clicked the run button at the top

**Comment by Zeolite2** [comment]
OK, thanks, I'll try again and I'll let you know if it works

**Comment by Zeolite2** [comment]
The only thing you have to do is to put the info in config.yml, right?

**Comment by XtramCZ** [comment]
ye

**Comment by Zeolite2** [comment]
OK, I'll try

**Comment by Zeolite2** [comment]
Now it says my token is invalid, even though it's coorrect, any idea how to resolve that, please help
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/91e12354-7067-442d-9e6a-e47223849a90)

**Comment by XtramCZ** [comment]
is it? Try here: https://discord-checker.janic.dev/

Replit may block the token since the code is public - Google how to setup env variables, that may help you.

**Comment by Zeolite2** [comment]
I see, but why does it work for you then, but not for me?

**Comment by Zeolite2** [comment]
I tried setting up env variables as google said, but after I run the command and click on "Run", nothing shows in the console. Can you check if everything I've put in the config is right.
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/330b5cca-a9a6-494b-b239-5498815bb346)

**Comment by XtramCZ** [comment]
Did you modify the code to use your env variables? This is a replit issue and a code issue so I can't really help you

**Comment by Zeolite2** [comment]
I ran the command here, after that nothing shows up. Can you please help me set it up on Replit since it worked for you, I really need it?
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/d942fc67-fe60-40d7-9738-975390fd1550)

**Comment by XtramCZ** [comment]
Maybe the `python main.py` or `python3 main.py`? I did not need to set this up.

**Comment by Zeolite2** [comment]
Didn't understand you. Where should I run this command?
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/2df7526b-823e-4b49-8c7e-3638e5e40455)

**Comment by XtramCZ** [comment]
in the "configure a run command" maybe ...?

**Comment by Zeolite2** [comment]
What should I run there? Which command?

**Comment by XtramCZ** [comment]
> Maybe the `python main.py` or `python3 main.py`? I did not need to set this up.

**Comment by Zeolite2** [comment]
I did it as you said, but it says again invalid token, event though it's right, I literally took before putting it right now. Any idea?
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/67d8f592-2f9c-4c03-aaf7-25fbe0090d76)

**Comment by XtramCZ** [comment]
Did you check the token on the site i sent you? 
Did you get a new one? 
Do you have 2fa?
Do you have phone verification? 
Did you set up env variables? D
id you change the code to take the token from the ENV variables and not config?

**Comment by Zeolite2** [comment]
when I run the ENV variables command "export varname=value" on the "Configure the Run Command" nothing shows up. What do I do?

**Comment by XtramCZ** [comment]
because instead of running the program ur exporting the var

**Comment by Zeolite2** [comment]
What do you mean. Can you please tell me step by step what should I do after I create a repl and import the code from github. Please bro, I really need help, please

**Comment by XtramCZ** [comment]
Looks like discord blocks replit's servers. I get the error "selfbots are against Discord's terms of service"
Unfixable. Sorry. Get a vps or a bot hosting.
Good luck.

**Comment by Zeolite2** [comment]
I see, can you guide me how to run it on my pc, like on the cmd, I'dont have a clue in coding.

**Comment by XtramCZ** [comment]
I can see that. The installation guide is in readme.md

**Comment by Zeolite2** [comment]
After I download the package, what should do to run it on the cmd, I literally don't have any idea of coding, please help

**Comment by XtramCZ** [comment]
The installation guide is in readme.md

pip install -r requirements.txt
then click start.bat or type python main.py in cmd

**Comment by Zeolite2** [comment]
but is that after I open the code in the cmd?

**Comment by XtramCZ** [comment]
?

**Comment by Zeolite2** [comment]
Bro, I literally don't know how to run the code on the cmd, can you tell me step by step, in readme.md it's only the basic info, for people that know how to run it, please tell me how to open in the cmd!

**Comment by XtramCZ** [comment]
btw do you even have python installed?

1. navigate to the folder in your file explorer
2. Click the bar at the top (where location is displayed) and type "cmd"
3. enter
4. type command `pip install -r requirements.txt`
5. enter
7. type command `python main.py`
8. enter
9. if that doesn't work, type the command `py main.py`
10. enter
11. if that doesn't work, exit out of the cmd and double click start.bat

**Comment by Zeolite2** [comment]
thank you

**Comment by Zeolite2** [comment]
I did it everything fine, but it says invalid token, even though I literally got it before putting it in. Any idea?
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/7c795b96-b0b2-4e94-9342-e6acf8f48186)

**Comment by Zeolite2** [comment]
I did it, everything fine, but when I run it, it says "ivalid token", even though I got it right before putting it in the config. Any idea?
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/7614febf-1379-4933-8a91-04cce9c87c78)

**Comment by XtramCZ** [comment]
> Did you check the token on the site i sent you? Did you get a new one? Do you have 2fa? Do you have phone verification? Did you set up env variables? Did you change the code to take the token from the ENV variables and not config?

**Comment by Zeolite2** [comment]
1. How do I check it there?
2. No, but I'll try a new one.
3. I don't have 2fa.
4. Yes, I do have a phone verification.
5. How do I set it up on the cmd?
6. I haven't because I haven't set ENV variables, because I don't know how, so please tell me.

**Comment by XtramCZ** [comment]
My bad, try this site: https://kanekiweb.github.io/Token-Checker/

You need env variables only on replit, not locally.

**Comment by Zeolite2** [comment]
So I don't need env variables when I run it on cmd, right?

**Comment by XtramCZ** [comment]
yes that's what i said

**Comment by Zeolite2** [comment]
I see and before I run the code in the cmd I need to put the info into the config file, right?

**Comment by XtramCZ** [comment]
..yes

**Comment by Zeolite2** [comment]
thanks

**Comment by Zeolite2** [comment]
Hey, I tried everything, even with different token, it still says, invalid token, I have python installed and everything, any idea? 
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/06d1d376-03f5-4d27-a836-42b2068235b4)

**Comment by XtramCZ** [comment]
Try new main.py and tell me what is displayed.

**Comment by XtramCZ** [comment]
Try the new main.py

**Comment by Zeolite2** [comment]
I tried it with the new code on Replit and it shows this (1st photo), even though my token is correct, after that I tried it on the cmd and it showed this (2nd photo)
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/700a6485-138d-4ef0-b361-502d48e0a43e)
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/cdba4271-ad8f-49b0-b6db-2edf719e9fcf)

**Comment by XtramCZ** [comment]
I already told you it does not work on replit.

Did you check your token on the website like I said? If you keep ignoring my advices then I'll close this issue

**Comment by Zeolite2** [comment]
It says it's invalid, what could be the reason, I literally got the token from the account before checking it?

**Comment by XtramCZ** [comment]
No idea, did you log off?

**Comment by Zeolite2** [comment]
no, I'm in the account, any idea?

**Comment by XtramCZ** [comment]
nope, idk

**Comment by XtramCZ** [comment]
you can try

**Comment by Zeolite2** [comment]
ok, I'll let you know, hope you canhelp me if it doesn't work

**Comment by Zeolite2** [comment]
OK, I have phone verification, but not 2fa, so I'll see

**Comment by Zeolite2** [comment]
I checked another token and it says it invalid too, even though it has phone verification and I got it literally right now. Any idea why it's invalid?
![image](https://github.com/XtramCZ/auto-advertise-py/assets/159666679/f2f7bb35-463c-4208-83da-7d96793c710d)

**Comment by XtramCZ** [comment]
No, sorry. You must be doing something wrong or you have a bad method of obtaining the token, are you doing it through console or "Application" tab in dev tools?

**Comment by Zeolite2** [comment]
I'm doing it from the "Application" tab in dev tools, is that the right way?

**Comment by XtramCZ** [comment]
I guess

**Comment by Zeolite2** [comment]
How do you suggest to do it?

**Comment by XtramCZ** [comment]
I never had problems doing it through Application. I'll leave this issue open if someone knows the fix
