### ISSUE TITLE
I've done everything carefully

### ISSUE THREAD

**Issue by Solaris-developer** [XtramCZ/auto-advertise-py#13]
![image](https://github.com/XtramCZ/auto-advertise-py/assets/145193611/f96f0722-572a-4965-8a9d-6dacde3d3bbf)
I've installed everything in the `requirements.txt` and I've configured everything to my liking. Is there a way I can fix this?

**Comment by XtramCZ** [comment]
open the .bat file and change py to python

**Comment by Solaris-developer** [comment]
How would I edit the file command?

**Comment by XtramCZ** [comment]
Open it in notepad perhaps?
