### ISSUE TITLE
cant install this image shows what shows to me

### ISSUE THREAD

**Issue by Rayan12131bro** [XtramCZ/auto-advertise-py#18]
![image](https://github.com/XtramCZ/auto-advertise-py/assets/165667031/e8c004c5-b9b5-403e-bdc2-4106f98eb5a7)

**Comment by Rayan12131bro** [comment]
when i try type it closes

**Comment by XtramCZ** [comment]
?

**Comment by XtramCZ** [comment]
edit the .bat file
