### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by adon1881** [XtramCZ/auto-advertise-py#20]
Not sending messages

**Comment by XtramCZ** [comment]
damn that sucks

errors?

**Comment by adon1881** [comment]
Nah got no error just not sending messages man

**Comment by XtramCZ** [comment]
Then I can't help you

**Comment by adon1881** [comment]
Oh alright man ill try this again lol

**Comment by adon1881** [comment]
Ye i did it wrong its working rn tysm man

**Comment by adon1881** [comment]
yo can you add auto dm reply? If yes thank you so much.

**Comment by XtramCZ** [comment]
I no longer work on this project, however i will still try to resolve errors.

I'm glad that it works :)

**Comment by adon1881** [comment]
Oh thanks man
