### ISSUE TITLE
Token is invalid

### ISSUE THREAD

**Issue by wilfredojrkuan** [XtramCZ/auto-advertise-py#4]
I'm using a user token not bot token, but Im getting Token is invalid. What seems to be the issue? I tried with the "" and without, same things happening

**Comment by XtramCZ** [comment]
Hi, discord may have changed your token for security reasons, try disabling 2fa and verify your account with a phone number. If not, you can try to regenerate your token by changing your password or try a different one (also please check your current token [here](https://kanekiweb.github.io/Token-Checker/))
