### ISSUE TITLE
Gateway error

### ISSUE THREAD

**Issue by alextefutee** [XtramCZ/auto-advertise-py#6]
![image](https://github.com/XtramCZ/auto-advertise-py/assets/157359949/37dd5480-7f52-44b5-8c2d-44973cbc5616)

**Comment by alextefutee** [comment]
Its spamming that error when its on that cooldown

**Comment by CernaKocka** [comment]
Does you status work?

**Comment by alextefutee** [comment]
Status? WDYM

> Does you status work?

**Comment by alextefutee** [comment]
> Are you online?

yes

**Comment by alextefutee** [comment]
After the bot is sending all the messages that error is spamming

**Comment by XtramCZ** [comment]
If it works it works, turn off debug mode to stop seeing it

**Comment by alextefutee** [comment]
it doesnt work, its showing that error and the ram is like over heating

**Comment by XtramCZ** [comment]
Can you elaborate?

**Comment by alextefutee** [comment]
![image](https://github.com/XtramCZ/auto-advertise-py/assets/157359949/5d415b88-9673-45e2-9128-113781456ac3)
![image](https://github.com/XtramCZ/auto-advertise-py/assets/157359949/ff484224-1bb4-4716-b4ee-22f064db8887)

**Comment by XtramCZ** [comment]
> it doesnt work,
Are you invisible on discord?

**Comment by alextefutee** [comment]
I am not invisible, the status is online

**Comment by alextefutee** [comment]
yes but why the error is spamming and is over heating my ram memory?

**Comment by XtramCZ** [comment]
It's not spamming in the new version, and it's taking ram beause it is trying to stay connected to the websocket

**Comment by alextefutee** [comment]
fixed
